### ISSUE TITLE
Should I backup secret.txt or not?

### ISSUE THREAD

**Issue by mhmdanas** [etesync/server#102]
[The README says "no"](https://github.com/etesync/server#secret_key-and-secrettxt) (emphasis mine):

> Make sure you keep the secret.txt file secret (don’t accidentally commit it to version control, **exclude it from your backups**, etc.).

[The wiki says "good idea, but not essential"](https://github.com/etesync/server/wiki/Backups#secrettxt):
> it's not required to back this one up to backup your data, but having a backup of this file will make it easier to restore the database to a new EteSync server. This secret is essentially only used for hashing the login password. So it's not essential, but probably good to back up.

**Comment by tasn** [comment]
The README is wrong, it's OK to back it up. The file is not very important though, it's only used for the admin login (though that can be reset). Probably best to back it up, but not include it in source control.

I'm closing this ticket as the quest has been answered, but please open a PR for the readme.
