### ISSUE TITLE
Reset endpoint

### ISSUE THREAD

**Issue by WhyNotHugo** [etesync/server#103]
Hi. I'm working on updating `vdirsyncer`'s testing suite to run with the latest etesync.

I'm trying to use the docker image `etesync/test-server`, but the `/reset` endpoint returns 404.

Do I have to do anything special to expose it? I tried looking into it, but I'm not sure how Django and FastAPI play together. I don't see [Django urls](https://github.com/etesync/server/blob/43d5af32d72d5f59de7f31698076becf2430ccaa/etebase_server/urls.py) for it, but it's mentioned in the [README](https://github.com/etesync/server/blob/43d5af32d72d5f59de7f31698076becf2430ccaa/README.md#testing).

**Comment by tasn** [comment]
This is where it's added: https://github.com/etesync/server/blob/master/etebase_fastapi/main.py#L45
You need to set DEVELOPMENT in order for it to be exposed.

**Comment by WhyNotHugo** [comment]
How exactly? I'm using:

```dockerfile
FROM etesync/test-server

ENV development=TRUE
ENV DEVELOPMENT=TRUE
```

And then:

```bash
docker build -t whynothugo/vdirsyncer-devkit-etesync .
docker run --rm -it -p 3735:3735 whynothugo/vdirsyncer-devkit-etesync
```

**Comment by tasn** [comment]
I think you need to put it either in the settings.py or the settings file. @daftaupe, do you remember the right way?

@WhyNotHugo, I'd expect test server to have it on alreday to be honest.

**Comment by WhyNotHugo** [comment]
`settings.py` already [has `DEBUG=True`](https://github.com/etesync/server/blob/43d5af32d72d5f59de7f31698076becf2430ccaa/etebase_server/settings.py#L32).

The test server also [has an ini file with `debug = true`](https://github.com/etesync/server/blob/43d5af32d72d5f59de7f31698076becf2430ccaa/docker/test-server/etebase-server.ini#L3).

**Comment by tasn** [comment]
Just to make sure, the path is: `/api/v1/test/authentication/reset/`

**Comment by WhyNotHugo** [comment]
:facepalm: I was using `/reset/`.

That was it. Oddly, `GET`ing to that endpoint return (and `/api` is not listed as known URLS:

![image](https://user-images.githubusercontent.com/730811/126212167-c9f5254b-9ac0-4325-ae4c-391bccdda3b0.png)

But `curl`ing works:

```console
$ curl -X POST http://localhost:3735/api/v1/test/authentication/reset/
{"detail":[{"loc":["body"],"msg":"field required","type":"value_error.missing"}]}%                                                             
```

**Comment by tasn** [comment]
Yeah, the known URLs isn't listing the right URLs as it doesn't show the API urls, but just the management UI.

For the API urls you should use: http://localhost:3735/docs
Btw, we use 3735 for the etesync-dav usually, so maybe not a good idea to occupy this URL.

Closing this as it's resolved.

**Comment by WhyNotHugo** [comment]
Thanks for the pointers!
