### ISSUE TITLE
still exist "wrong host name" error when I login in web client, use the latest package

### ISSUE THREAD

**Issue by aixiaofei** [etesync/server#105]
I login in web client based on the derect link (not use the nginx), but still got the "wrong host name"
![image](https://user-images.githubusercontent.com/23692423/131061110-4eab913b-e503-4156-9a0e-e59385ea223a.png)

this is my etesync server config:
![image](https://user-images.githubusercontent.com/23692423/131061203-1e5a39dd-b801-4daa-904a-230766267fb8.png)

**Comment by aixiaofei** [comment]
ok, Thank u, and I have added the port to allowed host, but got another issue:
![4969abcb7fc8a9bd4c49f8e597488d0](https://user-images.githubusercontent.com/23692423/131273095-17717e3e-2ac8-4329-8791-86c29f376e48.jpg)

![image](https://user-images.githubusercontent.com/23692423/131273120-38be0bfe-7d15-4dc1-aeb0-46bf9178719a.png)

I don't know why....

**Comment by tasn** [comment]
It' because you set it wrong, it should be:
```
[allowed_hosts]
allowed_host1 = xiaofei.online:64
allowed_host2 = 172.23.0.1:3735
```

**Comment by aixiaofei** [comment]
Thank u for your response
I have modified the configuration file
![image](https://user-images.githubusercontent.com/23692423/131319032-103e2cb9-e73b-4fbc-896d-17e61c27405b.png)

but still Bad request
![image](https://user-images.githubusercontent.com/23692423/131319113-1d2c4f6b-17fc-4fad-b976-1d8c108d6ce5.png)

**Comment by aixiaofei** [comment]
hello, I found the issue:
you will split the host in configuration file, so host_from_request will be host:port, but the validated_data.host always be host, so I think u need't to split or split both the validated_data.host and the host_from_request.

file: https://github.com/etesync/server/blob/master/etebase_fastapi/routers/authentication.py
![image](https://user-images.githubusercontent.com/23692423/132151546-82b080a3-4f00-4117-8d50-e4a38e477379.png)
