### ISSUE TITLE
licensing clarification

### ISSUE THREAD

**Issue by alepi** [etesync/server#115]
Hi,

I have seen that the server is AGPL licensed.

I am planning to use some Django apps together with the etebase server.

In my understanding the etebase license would force me to publish all of my code under a compatible open source license, possibly under the same license.

Would the author(s) be ok with allowing mixing etebase server with differently licensed Django apps, provided that they do not modify the etebase server code, or that changes to etebase are published under the same AGPL license?

In that case I think that it would be cool to add some kind of exception to the license allowing Django apps with all kinds of licenses to mix with etebase, in the same way that the linux kernel allows for non GPL apps to be loaded by the kernel.

**Comment by tasn** [comment]
You are right, the license is confusing like this. The intention was for *only* the changes to etebase itself to be made public. Not for the rest of the stack.

**Comment by tasn** [comment]
So yes, you have the premission.
