### ISSUE TITLE
Updating item is very slow (probably caused by having lots of revisions)

### ISSUE THREAD

**Issue by the-antz** [etesync/server#116]
Hi,

I use the etesync notes app since about one year and I have one note which I update multiple times a day. This specific note takes increasingly long to save while all other (less frequent updated) notes are saved quickly. All notes load fast.

I think it's a server side issue because I see the same behaviour when I update the item using the etebase-rs lib.

Updating the item takes about 4s (+-200 ms) (not using a transaction, no stoken) while other updates complete in about 200 ms pretty consistently.

I guess that this could also happen with collections with lot of revisions but I didn't test this.

**Comment by the-antz** [comment]
Seems fixed, thx!

**Comment by tasn** [comment]
👍🏻
