### ISSUE TITLE
Is the server abandonned ?

### ISSUE THREAD

**Issue by BirdInFire** [etesync/server#122]
is the developement / update of library are abandonned, since it's more than a year since last releast tag :  Dec 28, 2020
and more than 6 month since last commit ?

If we add the same ting (no update on ios in more than a year)

Cannot we (even if you say no) conclude that the dev is halted (for unknown reason) ?
(Because i do not believe than a server (and client in case of ios)) who handle encryption do not have update for more than 6 month).

**Comment by tasn** [comment]
Not abandoned, just not a lot of time to do things, and no burning issues. I and MANY others use it day to day.

There's no need to update things that just work. Encryption doesn't change, most of the encryption schemes in common use are over a decade old. Many or much much older than that.

So yeah, not a lot of development, but things continue to work and work well. :)
