### ISSUE TITLE
This ticket contains an incorrect report and a clickbait title [EDITED by @tasn]

### ISSUE THREAD

**Issue by BirdInFire** [etesync/server#123]
Please do your security update and stop hiding youself behind "it's work from decade blabla":

One proof your app isn't secure anymore since long one of the requirement of YOUR app : 

Will just take the exemple of django because since you don't secure your app don't try to bullshit me with your "it work like decade" : 

you use : django==3.1.4 

So i go see their changelog to see all security fix you don't HAVE and put the USERS WHO PAY YOU at risk : 

Django 3.1.6 fixes a security issue with severity “low” and a bug.
Django 3.1.7 fixes a security issue and a bug
Django 3.1.8 fixes a security issue with severity “low” and a bug
Django 3.1.9 fixes a security issue
Django 3.1.10 fixes a security issue
Django 3.1.12 fixes two security issues
Django 3.1.13 fixes a security issue with severity “high”
Django 3.1.14 fixes a security issue with severity “low”
Django 3.2.1 fixes a security issue and several bugs
Django 3.2.2 fixes a security issue and a bug
Django 3.2.4 fixes two security issues and several bugs
Django 3.2.5 fixes a security issue with severity “high” and several bugs
Django 3.2.10 fixes a security issue with severity “low” and a bug
Django 3.2.11 fixes one security issue with severity “medium” and two security issues with severity “low”
Django 3.2.12 fixes two security issues with severity “medium”
Django 4.0.1 fixes one security issue with severity “medium”, two security issues with severity “low”, and several bugs
Django 4.0.2 fixes two security issues with severity “medium” and several bugs

And since the main framework you use on server isn't updated, and the fact that ios and other isn't updated 3 conclusion are possible.

1. you don't know a thing about security, you stop sleeping and at least patch CVE...
2. you don't care and only want money without maintaining this and you aren't a good guy...
3. the dev have abandonned this and all other member are to lazy to maintain it...

In the 3 cases, this services is dead since it cannot provide the best security for his user.

**Comment by BirdInFire** [comment]
if i'm this harsh to you it's because i would like to use this service, but there is so many vulnerability i would be crazy to use it as it is now.
If i didn't care i would just have ignored the issue, you all member maybe time to correct this problem ?

Or you don't care about the project ?

**Comment by tasn** [comment]
@BirdInFire, I respect that, and following your comments we'll probably update django just for appearances, though it's important to state: we only use the Django ORM so we are **NOT AFFECTED** by most of these reports just based on that. Our API is powered by FastAPI.
As for the rest, we closely monitor security advisories for all of our deps and make sure that we are not affected.

**Comment by tasn** [comment]
Updated django to latest LTS. Though as I said, we were not affected by any of these.

**Comment by victor-rds** [comment]
@tasn could you release a new version tag? I want to try a way to automate the docker image update

**Comment by tasn** [comment]
Yes, gimme one sec.
