### ISSUE TITLE
Admins can reset user passwords, gaining access to their data

### ISSUE THREAD

**Issue by ggtylerr** [etesync/server#144]
Any admin can change a user's password in the admin panel:
![password change form](https://user-images.githubusercontent.com/28498877/172177882-31c20a5b-b68b-4c5f-b66d-dcd0d2e88d73.png)

This is dangerous, as anyone with admin perms can gain access to user data (albeit noticeable for the end user.) Also AFAIK there's no other way to change it on self-hosted servers.

**Comment by tasn** [comment]
This is incorrect. Try it, and you'll see...

This dialog is only for managing admin accounts, though since in EteSync/Etebase everything is encrypted client-side this sever password doesn't actually matter. This isn't even used for authentication of EteSync clients, but rather a zero-knowledge proof is.

Closing as incorrect.

**Comment by tasn** [comment]
It's more effort to remove this dialog than it's worth as it doesn't actually do anything for non-admin accounts.

Not sure what you mean by no way to change passwords, but you can change the encryption password in any of the client. It has to be done client side due to e2ee.

**Comment by tasn** [comment]
I don't understand what you mean. Can you try explaining from the top? What are you after? Wiping a self-hosted account?

**Comment by ggtylerr** [comment]
Pretty much. I know deleting is possible but it's not very viable for production.

**Comment by tasn** [comment]
Yeah, the easy way to do it in the repo at the moment is just renaming the user. There isn't an easy way to wipe the data in the open source repo at the moment.

**Comment by Benjamin-Loison** [comment]
Concerning [#issuecomment-1147711200](#issuecomment-1147711200), see #84.
