### ISSUE TITLE
Unable to access EteSync

### ISSUE THREAD

**Issue by catwithbanana** [etesync/server#146]
As of this morning, my email client reports the following error:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/75995110/174488661-1508c952-d9b5-442d-ab28-2de52a756fc0.png">

When I try to log into the server management in my browser my credentials are not accepted. Trying to log into the web interface via etesync.com gives this error:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/75995110/174488692-cdce2449-e894-4dd9-9dc9-58785d764d33.png">

Meanwhile I am unable to view or edit my calendar -- a debilitating issue.

Please let me know if there's anything I can do to resolve this issue. Thanks.

**Comment by catwithbanana** [comment]
My email client is now reporting an internal server error
<img width="586" alt="image" src="https://user-images.githubusercontent.com/75995110/174489711-c5165cd1-7086-43bf-bbc6-7518e6b1b726.png">

I continue to get a "network request failed" error when trying to log into the web interface via any device, so I can't access my calendar from anywhere.

**Comment by catwithbanana** [comment]
It's now working again, but I'll leave this open in case there is any insight to be shared on why things went down for an hour.

**Comment by tasn** [comment]
Sorry for the trouble, and as you said, it's now fixed.

This is the updated we posted on twitter (after you opened the ticket): https://twitter.com/EteSyncHQ/status/1538597067169447936

I'm going to close it now, thanks for opening it though!

**Comment by catwithbanana** [comment]
@tasn EteSync worked as expected for the past 5 hours, but unfortunately it is spitting the same errors again.

**Comment by tasn** [comment]
I reopened the ticket.

**Comment by tasn** [comment]
Things seem to be fully fixed now, though we are continuing to monitor the situation.
