### ISSUE TITLE
django 3 end-of-life

### ISSUE THREAD

**Issue by felschr** [etesync/server#173]
django 3 support is scheduled to end on 2024-04-01: https://endoflife.date/django

Etebase server should be updated to django 4 (or 5 once released) to prevent issues e.g. with downstream packages.

Downstream NixOS issue: https://github.com/NixOS/nixpkgs/issues/262907

**Comment by felschr** [comment]
EOL has been pushed back slightly to 2024-04-30.
Still, it's just a little more than a month away.

**Comment by shimunn** [comment]
Etesync is end to end encrypted, precisely for this reason, not having to trust the server. Additionally for an software to be eol does not imply insecure straight away.

**Comment by tasn** [comment]
The annoying this is that we don't really use Django almost at all, it's just for the ORM.

I could have sworn there was a ticket somewhere else by someone working on converting the queries to SQLAlchemy.

**Comment by tasn** [comment]
Done, sorry for the delay!

I was hoping we would be on SQLAlchemy by now, but I guess upgrading it to version 4 until that happens is better.
