### ISSUE TITLE
Cannot remove user

### ISSUE THREAD

**Issue by clamydo** [etesync/server#174]
When I try to remove a user in the django admin panel `test` I get the error:
```
Cannot delete users

Deleting the selected users would require deleting the following protected related objects:

      Collection member: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx test
      Collection member: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx test
      Collection member: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx test
      Collection member: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx test

```
with some random string in place of the `x`es.

How do I delete a user?

And many thanks for creating EteSync/EteBase!

**Comment by jahway603** [comment]
Having the same issue. Duplicate of Issue https://github.com/etesync/server/issues/84

**Comment by jahway603** [comment]
Workaround is to set the account to Inactive by unchecking the Active checkbox in the account's settings screen.

**Comment by clamydo** [comment]
Closing in favor of #84

**Comment by tasn** [comment]
Thanks both!
