### ISSUE TITLE
Expose STATIC_ROOT and other settings in etesync-server.ini

### ISSUE THREAD

**Issue by eomanis** [etesync/server#24]
After some days of fiddling I have been successful in setting up an nginx-uwsgi EteSync server instance on Arch Linux from the [etesync-server AUR package](https://aur.archlinux.org/packages/etesync-server/).

The setup works well, but I had to edit the package-shipped `settings.py` file to set a custom `STATIC_ROOT`, and this is inconvenient insofar as this file will be overwritten on each package update and I have to be mindful to edit it on every such occasion.

I do not quite trust my future self enough to remember this, and it would for my use case be convenient if I were able to specify a custom `STATIC_ROOT` in `etesync-server.ini`.

While we are at it, other users might wish to set other variables there as well, possibly these:

- `STATIC_URL`
- `LANGUAGE_CODE`
- `TIME_ZONE`

Implementing this would likely encompass these changes to `settings.py`:

- Extend the section that reads the `etesync-server.ini` file(s) accordingly
- Move the "Internationalization" and "Static files" sections above the section that reads the `.ini` file(s)

I am aware of the section at the bottom that attempts to import an `etesync_site_settings` Python module, but as someone who is not at all familiar with Python or with the rules of where Python looks for modules I figured I might ask about extending `etesync-server.ini` before I attempt to go down that road.

**Comment by tasn** [comment]
Thanks for the report. Shouldn't be too hard!

cc @daftaupe

**Comment by daftaupe** [comment]
True, these settings should be available through the .ini file as well. I'll try to find the time to look at that soon.

**Comment by eomanis** [comment]
Aw yiss!
Works as advertised with Arch Linux [etesync-server-0.3.0-1](https://aur.archlinux.org/packages/etesync-server/).

One thing less to keep in mind, thanks.
