### ISSUE TITLE
Running etesync in systemd

### ISSUE THREAD

**Issue by dducted** [etesync/server#25]
Hi there,

I tried to run etesync in systemd, its starts well however server appears to be down. Used the following code:

```
[Unit]
Description=EteSync
After=multi-user.target

[Service]
ExecStart=/home/ubuntu/server-skeleton/venv/bin/python /home/ubuntu/server-skeleton/./manage.py runserver 0.0.0.0:8000
User=ubuntu
Group=ubuntu
Type=idle
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target
```

Does anything look wrong to you? I was sadly not able to spot the issue. Thanks for your help!

**Comment by dducted** [comment]
I was able to resovle the issue myself.

**Comment by tasn** [comment]
Great news, could you please share what you did to make it work? Would be great to know in case anyone else is having issues.

**Comment by dducted** [comment]
Sure. Please find my working systemd file below:

```[Unit]
Description=EteSync
After=multi-user.target

[Service]
WorkingDirectory=<path to etestnc>
User=ubuntu
Group=ubuntu
ExecStart=<path to etestnc>/venv/bin/python ./manage.py runserver 0.0.0.0:8000
Type=idle
Restart=always
RestartSec=15

[Install]
WantedBy=multi-user.target```

**Comment by tasn** [comment]
Thanks!

P.S, the Django people don't recommend using the debug server (`./manage.py runserver`) in production, but rather recommend using uwsgi. There's a uwsgi config in the examples directory. Consider using it (you can also tell it to server http or port 8000 rather than unix socket).

**Comment by dducted** [comment]
Thanks for pointing that out. I've never used uwsgi  but I'll give it a shot.
