### ISSUE TITLE
Federated: Allow anyone to host a server

### ISSUE THREAD

**Issue by trymeouteh** [etesync/server#36]
I know your able to host a eyesync server for yourself, however it will be great if you allow anyone to host it as a service. This way anyone can host a etesync service, choose the free storage size, free trail period length, paid account price, etc.

I am not against etesync but this will make the etesync ecosystem federated which will reduce censorship and allow anyone to host a etesync service and set their own rules. Simular to how Mastodon and Peertube works but for contacts and calendars.

**Comment by tasn** [comment]
This is out of scope for this project. You can (and many people do!) host your own server, just like Mastodon.

It's the same way that Mastodon doesn't include billing code to let you charge users, neither does EteSync...
