### ISSUE TITLE
please provide (more explicit) copyright and licensing

### ISSUE THREAD

**Issue by jonassmedegaard** [etesync/server#37]
It is difficult to guess who hold copyright for which parts of this project, and which licensing terms those copyright holders grant for which parts.
Please consider adding copyright + licensing boilerplate on top of all code files (and if adding PNG or SVG files then embed such information as EXIF or RDF data as appropriate).

Similar issue: https://github.com/etesync/etesync-dav/issues/114

**Comment by tasn** [comment]
Are you also packaging the server? Because if so, I guess you'd also like me to fix https://github.com/etesync/journal-manager ?

**Comment by jonassmedegaard** [comment]
I'd like you to fix all sloppy licensing issues you know of, globally :-)

...but yes, addressing journal-manager first is nice, because you guessed right: I _am_ packaging the server for Debian as well.

**Comment by tasn** [comment]
I'm actually against license headers in code in general, and usually I push back, but I know Debian are a bit specific about these things, and so I'd rather just comply for things that get packaged for that.

I had a long discussion about it last week at FOSDEM. :P

Anyhow, everything that's relevant is now fixed. P.S, I sent you an email regarding the packaging, please take a look when you have a moment.

**Comment by jonassmedegaard** [comment]
Quoting Tom Hacohen (2020-02-14 15:47:27)
> I'm actually against license headers in code in general, and usually I 
> push back, but I know Debian are a bit specific about these things, 
> and so I'd rather just comply for things that get packaged for that.
> 
> I had a long discussion about it last week at FOSDEM. :P

I am sorry if my reported issues has given (or confirmed) an impression 
that Debian _mandates_ a certain style of stating copyright and 
licensing.  What I meant to say was only that (in my work of preparing 
packaging for Debian) I noticed uncertainties and would encourage 
clarifying those.

While I do think that license headers in code makes great sense, it is 
_not_ a requirement for inclusion in Debian: Debian requires freely 
licensed code, but that is possible in multiple ways. You can even 
totally omit mentions of copyright and licensing in the whole project, 
and just explain to me in casual english what that information is - e.g. 
in an email - and I could then include with the Debian package a copy of 
that email from you as proof of the copyright and licensing which 
applies for that code project.


> P.S, I sent you an email regarding the packaging, please take a look 
> when you have a moment.

I haven't received that.  Please use my preferred email address 
dr@jones.dk or if that fails then try js@debian.org

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by tasn** [comment]
> Quoting Tom Hacohen (2020-02-14 15:47:27)
> I'm actually against license headers in code in general, and usually I push back, but I know Debian are a bit specific about these things, and so I'd rather just comply for things that get packaged for that. I had a long discussion about it last week at FOSDEM. :P
> I am sorry if my reported issues has given (or confirmed) an impression that Debian _mandates_ a certain style of stating copyright and licensing. What I meant to say was only that (in my work of preparing packaging for Debian) I noticed uncertainties and would encourage clarifying those. While I do think that license headers in code makes great sense, it is _not_ a requirement for inclusion in Debian: Debian requires freely licensed code, but that is possible in multiple ways. You can even totally omit mentions of copyright and licensing in the whole project, and just explain to me in casual english what that information is - e.g. in an email - and I could then include with the Debian package a copy of that email from you as proof of the copyright and licensing which applies for that code project.

Oh, I guess I misremembered from my previous interactions with Debian. I was thinking specifically at https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Anyhow, doesn't matter, I added the licensing headers now for these, so we should be good. :)

**Comment by tasn** [comment]
Did you see my email now? If not, could you maybe email me at my first name at etesync.com?
