### ISSUE TITLE
Can we force the super user password to be changed on first login?

### ISSUE THREAD

**Issue by peter-stadler** [etesync/server#38]
I am looking for the creation of a package on OpenWrt. It would be nice, if we can install a superuser such that its password must be changed, when visiting `/admin/login` the first time.

Something like setting the password to `unusable` and force a change on the LoginView, like described at [SO](https://stackoverflow.com/questions/53125468/django-force-a-user-to-reset-initial-password).

Unfortunately, I do not know much about Django.

Do you think, this would be a good idea at all?

**Comment by tasn** [comment]
As I said in https://github.com/openwrt/packages/pull/9865#discussion_r389182406
It's not supported out of the box and requires extra code. I think it may be easier to just let the user create a password, or create a random password for them upon installation as suggested in the PR.

Let's have the discussion there, so I'm closing this ticket. Let me know if you think I should reopen it.
