### ISSUE TITLE
Feature Request: Comprehensive Installation Guide

### ISSUE THREAD

**Issue by BeatLink** [etesync/server#41]

**Comment by tasn** [comment]
There is information on the wiki and the readme, but I understand from you on IRC that you have something already? Maybe you could share that?

**Comment by tasn** [comment]
I just realised there is one on the wiki.... https://github.com/etesync/server/wiki

Please make suggestions for updating it if you have anything. I'm closing it in the meanwhile. Let me know if you have some concrete improvement ideas.
