### ISSUE TITLE
manually backup personal data

### ISSUE THREAD

**Issue by dreamstr1ker** [etesync/server#43]
get etesync server self-hosted and running , wanna write some cron job to backup data( calendar,contacts,tasks) everyday,
is jsut backing up /server-skeleton/db.sqlite3 enough?
should I backup secret.txt?

don't know if there is the proper place to throw those question though, sorry if I broken some rules.

**Comment by tasn** [comment]
Hey! The right place for this kind of questions is either the IRC channel, or reddit. Just so you (and others reading this) know for next time. :)

As for your question: yeah, backing up that file is sufficient. You should probably back it up by running: `sqlite3 my_database.sq3 ".backup 'backup_file.sq3'"`
See https://stackoverflow.com/questions/25675314/how-to-backup-sqlite-database for more information.

As for `secret.txt`: it's not required to back this one up to backup your data, but having a backup of this file will make it easier to restore the database to a new etesync server. This secret is essentially only used (if memory serves) for hashing the login password. So it's not essential, but probably good to back up.

**Comment by daftaupe** [comment]
@dreamstr1ker ,

I've created a wiki page https://github.com/etesync/server/wiki/Backups regarding this issue.
If anything is missing, feel free to edit.
