### ISSUE TITLE
Server Error 500 after Login in Django Admin Backend

### ISSUE THREAD

**Issue by lucollab** [etesync/server#44]
Hey there, 

i installed etesync on a debian vps with these tutorials in combination:

- https://simonvandevelde.be/Guides/html/Tutorials/etesync.html#etesync-server
- https://github.com/etesync/server
- https://github.com/etesync/server/wiki/Production-setup-using-uWSGI-and-Nginx

When i am opening my browser and go to https://etesync.mydomain.de/admin/ i can see my django admin backend. When i am trying to login i get the error "Server Error (500)". I am not that used to django or virtualenv so i am really struggeling finding the error... Do someone have an idea?

I attached my config files.
[etesync_nginx.conf.txt](https://github.com/etesync/server/files/4564823/etesync_nginx.conf.txt)
[uwsgi.ini.txt](https://github.com/etesync/server/files/4564827/uwsgi.ini.txt)
[etesync-server.ini.txt](https://github.com/etesync/server/files/4564828/etesync-server.ini.txt)

Thanks for your help!
Lukas

My Steps are these:
1.
- sudo apt-get update && sudo apt-get upgrade
- sudo ufw allow 8000
- sudo ufw allow 8001

2.
- sudo apt-get install python3-pip git
- pip3 install virtualenv

or
- apt-get install python3-virtualenv

3.
- cd /home/luke
- git clone https://github.com/etesync/server-skeleton.git
- cd server-skeleton

4.
- virtualenv -p python3 venv
- source venv/bin/activate

5.
- pip3 install -r requirements.txt

6.
- cp etesync-server.ini.example etesync-server.ini

7.
- nano etesync-server.ini

edit to:
```
[global]
secret_file = secret.txt
debug = false

[allowed_hosts]
allowed_host1 = *

[database]
engine = django.db.backends.sqlite3
name = db.sqlite3
```

8.
-  ./manage.py migrate
-  ./manage.py runserver 0.0.0.0:8000

9.
Reachable under: http://etesync.mydomain.de:8000/
und: http://94.130.226.255:8000/

10.
stop debug server with control+c

11.
- apt-get install build-essential python3-dev
- sudo pip3 install wheel

13.
- sudo pip3 install uwsgi

14. testing:
- cd /home/luke/server-skeleton/
- source venv/bin/activate
- uwsgi --http :8000 --module etesync_server.wsgi --virtualenv venv

stop with control+c

15.
- sudo -s
- cd /home/luke/server-skeleton/
- source venv/bin/activate

16.
- ./manage.py collectstatic

17.
- nano etesync_nginx.conf

Edit:

```
upstream django {
    # server unix:///tmp/etesync_server.sock; # for a file socket
    server 127.0.0.1:8001; # for a web port socket (we'll use this first)
}

server {
    # the port your site will be served on
    listen      8000;
    # the domain name it will serve for
    server_name etesync.mydomain.de; # substitute your machine's IP address or domain name
    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    location /static {
        alias /home/luke/server-skeleton/static; # Project's static files
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass  django;
        include     /etc/nginx/uwsgi_params; # the uwsgi_params file, this path by default
    }
}
```

18.
- sudo cp etesync_nginx.conf /etc/nginx/sites-available/
- sudo ln -s /etc/nginx/sites-available/etesync_nginx.conf /etc/nginx/sites-enabled/etesync_nginx.conf
- systemctl restart nginx

- uwsgi --socket :8001 --module etesync_server.wsgi
- (wokring: uwsgi --http :8001 --module etesync_server.wsgi --virtualenv venv)

19.
- sudo nano /etc/nginx/sites-available/etesync_nginx.conf

Edit:
```
upstream django {
    server unix:///tmp/etesync_server.sock; # for a file socket
    # server 127.0.0.1:8001; # for a web port socket (we'll use this first)
}
```

20.
- sudo nano uwsgi.ini

Edit:
```
[uwsgi]
chdir = /home/luke/server-skeleton/
socket = /tmp/etesync_server.sock
chown-socket = luke:www-data
chmod-socket = 660
module = etesync_server.wsgi
master = true
uid = luke
virtualenv = venv
```

21.
- (venv) luke@meeting:~/server-skeleton$ sudo uwsgi --ini uwsgi.ini

22.
- sudo nano /etc/systemd/system/etesync_server.service

Edit:
```

[Unit]
Description=Execute the etesync server.

[Service]
ExecStart=/usr/local/bin/uwsgi --ini /home/luke/server-skeleton/uwsgi.ini

[Install]
WantedBy=multi-user.target

```

23.
- sudo apt install policykit-1
- systemctl start etesync_server
- systemctl enable etesync_server

24.
- sudo certbot --nginx

25.
- cd /home/luke/server-skeleton/
- source venv/bin/activate
- ./manage.py createsuperuser

26. Django Backend has no css... repairing:
- root@meeting:/home/luke/server-skeleton# nano etesync-server.ini

Edit:
`static_root = /home/luke/server-skeleton/static`

- (venv) root@meeting:/home/luke/server-skeleton# ./manage.py collectstatic

27. server 500 error?

**Comment by lucollab** [comment]
With debug true i can login and get the following:


Request Method: | POST
-- | --
https://etesync.mydomain.de/admin/login/?next=/admin/
2.2.12
OperationalError
attempt to write a readonly database
/home/luke/server-skeleton/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 383
/usr/local/bin/uwsgi
3.5.3
['.',  '',  '/home/luke/server-skeleton/venv/lib/python35.zip',  '/home/luke/server-skeleton/venv/lib/python3.5',  '/home/luke/server-skeleton/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/luke/server-skeleton/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/luke/server-skeleton/venv/lib/python3.5/site-packages']
Fri, 1 May 2020 15:49:39 +0000

**Comment by lucollab** [comment]
And: 
i can only open the https://etesync.mydomain.de/admin/ page, if i add * to my allowed hosts. All other allowed hosts (IP of the server or the domain etesync.mydomain.de) get the Error Bad Request 400. Like here: https://github.com/etesync/server/issues/18

So with * i get Server 500 Error because of not writeable DB?
And with my "real" Hostname or IP i get Bad Request...

**Comment by lucollab** [comment]
When i put the rights on the whole folder with:

chmod -R 757 server-skeleton/

than i get:

```
Request Method: | POST
-- | --
https://etesync.lukasschick.de/admin/login/?next=/admin/
2.2.12
OperationalError
unable to open database file
/home/luke/server-skeleton/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py in execute, line 383
/usr/local/bin/uwsgi
3.5.3
['.',  '',  '/home/luke/server-skeleton/venv/lib/python35.zip',  '/home/luke/server-skeleton/venv/lib/python3.5',  '/home/luke/server-skeleton/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/luke/server-skeleton/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/luke/server-skeleton/venv/lib/python3.5/site-packages']
Fri, 1 May 2020 16:06:32 +0000
```

**Comment by daftaupe** [comment]
Hello @lucollab,

I think you get the error in the case where you have '*' because in the other case EteSync doesn't treat the requests it receives from your reverse-proxy, because theses requests are not allowed with the configuration you have setup.

So 2 things :
- you probably need a X-forwarded-for or a proper Host header to be passed to your backend to be able to use your web domain name as an "allowed_host". Something like proxy_set_header Host $host; or proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
- you certainly have an issue that the user under which you run uwsgi has no write access to the database

**Comment by tasn** [comment]
@daftaupe's answer looks correct. I don't understand why you would get "non-writeable db" error though. Maybe also uwsgi is running the server with a user different to the one you expect?

**Comment by lucollab** [comment]
Thanks a lot for your help - I must have gotten a little confused. I have switched to the debian script in the meantime. After some small adjustments this works fine now. We can close this issue here.

**Comment by tasn** [comment]
Great to hear. Thanks for the update!

**Comment by plsnotracking** [comment]
I hit the `500` issue as well but I don't see the error messages that @lucollab saw. I was wondering what other ways could I `debug` this?

Here's my nginx config if it helps:
```
# mysite_nginx.conf

# the upstream component nginx needs to connect to
upstream django {
    server unix:///tmp/etesync_server.sock; # for a file socket
    # server 127.0.0.1:8001; # for a web port socket (we'll use this first)
}

# configuration of the server
server {
    # the port your site will be served on
    listen      8000;
    # the domain name it will serve for
    server_name etesync.domain.com; # substitute your machine's IP address or domain name
    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    location /static/ {
        alias /path/to/server-skeleton/static/; # Project's static files
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass  django;
        include     /etc/nginx/uwsgi_params; # the uwsgi_params file, this path by default
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot

    ssl_certificate /etc/letsencrypt/live/etesync.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/etesync.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    error_log /var/log/nginx/eteysnc.domain.com.err_log;
}
```

I do get the `it works` message.

One more thing I came across as maybe an issue (https://github.com/etesync/server/wiki/Production-setup-using-uWSGI-and-Nginx#setup-nginx) was with the `location /static/ {`

`alias /path/to/server_skeleton/static; # Project's static files`
^ this line seems to miss a trailing `/` because after adding that `/` my Django backend seemed to be prettier.

Thank you for making this project.

**Comment by tasn** [comment]
Edit the configuration and set debug to true, and then you'll see what's wrong. It's most likely a permission issue.
If you still can't figure it out, come to https://www.etesync.com/comunity-chat/ and chat with us. It's almost certainly an error with your setup rather than with etesync itself.

**Comment by Roost-surface-to-air** [comment]
I experienced a similar issue and worked through it to find a solution https://data-fitting-slot9.github.io/CymIim7kwbIcV0uWHoMsfE4DdGiqLrBYhT/
