### ISSUE TITLE
Feature Request: Support Shared Calendars / Lists

### ISSUE THREAD

**Issue by jtrees** [etesync/server#45]
EteSync looks amazing! I really want to switch from Fruux to EteSync but calendar and list sharing (read-only and/or read-write) is the one feature that's keeping me away. Is it on the roadmap?

**Comment by tasn** [comment]
Hey, it's already implemented and has been there since almost day 1. :)
You can share with any other account from any of the etesync apps except for etesync-dav.

**Comment by jtrees** [comment]
Wow! I simply missed it in the GUI. You've some new subscriptions incoming.
