### ISSUE TITLE
iOS 13.5.1 app "NetworkError"

### ISSUE THREAD

**Issue by n1ete** [etesync/server#46]
i got trouble to connect with the an selfhosted etesync-server in the etesync ios app.

weblogin over  etesync-web and admin-ui works fine though.

i specified 
`username`
`password`
`https://local.server:8080`

and recieved:
```
Error
NetworkError: Network request failed
```
i activated debug logs but there is nothing besides of
`[I] ConnectionfInfo: true wifi`

devices is reachable and i can login from the iPhone via Mobile Browser.
any ideas how to debug this further?
thanks

**Comment by tasn** [comment]
Are you using a self-signed cert? If I remember correctly that's a limitation with react-native (which we use). Could you maybe try using HTTP (just for testing)?

**Comment by n1ete** [comment]
jepp, with plain http it is working. so any chance to make it work with an self-isigned cert? import and trusting the crt on ios does not seem to work either.
usually i dont have etesync-server facing to "public" and prefer a self signed cert as more secure...
thanks for right hint!

**Comment by tasn** [comment]
I wish we could, though if I remember correctly it's a limitation with react-native. ;\

**Comment by lonkaars** [comment]
I got etesync with https working on ios 13.4.1. If I remember correctly, you also need to trust the certificate in settings > about > 'certificate trust settings' to get the certificate to work outside of safari. Hope this helps!

**Comment by tasn** [comment]
Oh, that's great, thanks @lonkaars!
@n1ete, could you please let me know if it works and I'll make sure to add it to the guide?

Thanks!

**Comment by n1ete** [comment]
@tasn @lonkaars thanks for this i just added the cert and didnt hit the switch, but unfortunatly nothing changed :-(

**Comment by lonkaars** [comment]
@n1ete Not sure what you mean, [here's](https://youtu.be/g_zaBffRP-w) a video of what I tried to explain. (sorry for the sloppy censor job, pls don't steal my credentials)

**Comment by n1ete** [comment]
sry for my lack of english skills,
what i tried to explain was, that its not working even with the trust switch flipped to trust.....

**Comment by n1ete** [comment]
after reinit the hole setup with a new cert its working! thanks for your help and time
