### ISSUE TITLE
Nginx with uwsgi on subdirectory not completely working

### ISSUE THREAD

**Issue by gianfrappe** [etesync/server#50]
Hi!
I'm trying to setup etesync under a "subdirectory" using nginx and uwsgi.
For the sake of completeness, I'm using [this](https://hub.docker.com/r/victorrds/etesync) docker image for etesync.
Now... If I go to the domain, appending "/etesync" to it (so say mydomain.com/etesync), the page "It works!" appear. However, If I go to "/etesync/admin", it go back to "/admin", effectively not showing the admin page. This is the nginx configuration I'm using.
I also tried setting "ETESYNC_DAV_URL=/etesync". Doing so, also "BASE_DIR" appear to be the same.
```
upstream django {
    # server unix:///tmp/etesync_server.sock; # for a file socket
    server 192.168.1.4:3735; # for a web port socket (we'll use this first)
}

server {
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;

        root /config/www/mydomain.com;
        index index.html index.htm index.php;

        server_name mydomain.com;
        
        location /etesync {
            return 301 $scheme://$host/etesync/;
        }

        location ^~ /etesync/ {
            uwsgi_pass  django;
            include     /etc/nginx/uwsgi_params; # the uwsgi_params file, this path by default

            proxy_set_header  X-Script-Name /etesync;
            proxy_set_header SCRIPT_NAME /etesync;

            rewrite /etesync(.*) $1 break;

            proxy_redirect off;
            proxy_buffering off;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_cookie_path / "/; HTTPOnly; Secure";
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }

        # all ssl related config moved to ssl.conf
        include /config/nginx/ssl.conf;

        client_max_body_size 75M;

        location / {
                try_files $uri $uri/ /index.html /index.php?$args =404;
        }
}
```
However, if I use etesync on the domain directly, without the subdirectory (and not setting the environment variable), everything loads! So I'm surely missing something here. The configuration that works on the domain is the following:
```
# DJANGO FROM ABOVE

server {
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;

        server_name mydomain.com;

        # all ssl related config moved to ssl.conf
        include /config/nginx/ssl.conf;

        client_max_body_size 75M;

        location / {
            uwsgi_pass  django;
            include     /etc/nginx/uwsgi_params; # the uwsgi_params file, this path by default

            proxy_redirect off;
            proxy_buffering off;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_cookie_path / "/; HTTPOnly; Secure";
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
        }
}
```
Hope somebody have an idea.

**Comment by daftaupe** [comment]
Hello,

in the case where you use /etesync, I'm not sure these two sections should be in the configuration :

```        
        location /etesync {
            return 301 $scheme://$host/etesync/;
        }
```

and
 
```
        rewrite /etesync(.*) $1 break;
```

Did you check this page : https://github.com/etesync/server/wiki/Production-setup-using-uWSGI-and-Nginx ?

I think you would just have to change `location /` by `location /etesync/` in it.

Don't hesitate to come on the irc canal if you want to help with the configuration, it's much easier than on a Github issue.

**Comment by tasn** [comment]
@daftaupe, that should suffice except for admin. The EteSync API has no assumptions about where it lives, but django itself (the admin) does make such an assumption.
You are on the right path with SCRIPT_NAME, and it should have worked, I think. Maybe try forcing it from django: https://docs.djangoproject.com/en/3.1/ref/settings/#force-script-name

I'm not sure to be honest, please check with the django people on what's the correct way of doing it.

I'm closing this ticket as we don't officially support running etesync under a sub-path.

**Comment by cRoCx** [comment]
I'm having the same issue. Would really like to see a working solution.
It's a pity having to create an new subdomain. All the other services I use support being served from a subdirectory and I am desperately trying with this project right now.

**Comment by tasn** [comment]
Running from the subpath has adverse security implications (sharing cookie, can send the auth token to the wrong domain, etc). Though also, it's just not how most things are meant to work. I won't object to a PR that adds official support for it, but it's not on the immediate roadmap.
