### ISSUE TITLE
DisallowedHost Error

### ISSUE THREAD

**Issue by bitog** [etesync/server#57]
Hi,

I just tried to install EteSync, never had any issues installing an older EteSync version, but it seems 2.0 is not working as expected.

I am always left with:

```
DisallowedHost at /
Invalid HTTP_HOST header: 'mydomain'. You may need to add 'mydomain' to ALLOWED_HOSTS.
```

In `etesync-server.ini` I have set `allowed_host1 = mydomain`. Unsure why I am not able to visit the website. As mentioned I never experienced such issue with previous versions. Installation went just smooth.

Thanks for your help!

**Comment by tasn** [comment]
It should be `etebase-server.ini`. Sorry for the confusion, it was renamed when we renamed the rest of this repo.

**Comment by bitog** [comment]
Oh ok, thanks for the clarification - worked!

**Comment by tasn** [comment]
Great to hear, and thanks for the update!
