### ISSUE TITLE
Apache Self hosted server

### ISSUE THREAD

**Issue by smarkars** [etesync/server#60]
I have hosted the server and created the superuser with password. I'm able to login into the both notes and sync app in Android and iOS. But from the [Usage](https://github.com/etesync/server#usage) section it is mentioned that  "_create a new user to be used with the service. Do not set a password for the user, as Etebase uses a zero-knowledge proof for authentication._". When I navigate to my domain https://domain/admin i see the DJango login page. I can use the super user but I'm not able to create an use without a password. Can you please direct me to any resource on how to do that?

Is it safe that having a super user at all?
If so I’m connecting the sync server with that password that means anyone who has the access to the sqlite db  can unlock it?

Thanks!

**Comment by tasn** [comment]
Having a superuser: yeah, that's safe and fine. Also, if it's just you using the server, there probably isn't a problem using it as the superuser.

As for guide: just fixed it, thanks!
