### ISSUE TITLE
HTTP error 400! Code: 'wrong_host'

### ISSUE THREAD

**Issue by jdckr** [etesync/server#66]
Hi!
I tried to migrate to Etesync 2.0 but when trying to connect to the server using the android client I get the error:
```
HTTP error 400! Code: 'wrong_host'.
Detail: 'Found wrong host name. Got:
"etesync.user.host.net" expected "user.local.host.net:<port>"
```
Due to the infrastructure of the hoster I use, I have a apache rewrite rule which maps the global url `etesync.user.host.net` to the internal url `user.local.host.net:<port>`. I have added the global url to `CSRF_TRUSTED_ORIGINS` and the local one to `allowed_hosts`. The setup works fine with the old server, but doesn't work with Etesync 2.0

I already checked views.py but wasn't able to find out which settings might help to get rid of this error.

**Comment by tasn** [comment]
What version are you using? I believe I fixed this in 843b59a0ac1e2076a514b9c52fc5c6941b27dff0

I'll just release 0.5.2 with the fix.

**Comment by jdckr** [comment]
I tried with 0.5.1. Release 0.5.2 will unfortunately not solve the problem as the fix you linked only strips off the port. In my case the problem is that the base url itself is different:
* global: **etesync**.user.host.net 
* internal:   **local**.user.host.net:**\<port>**

**Comment by tasn** [comment]
Ahh, sorry, I misread. What you need to do in order to fix this is to force the HOST header in your reverse proxy so that the etebase server gets the public hostname.
Here is how I do it here locally on my dev environment (using nginx):
```
    proxy_set_header Host api.etebase.com;
```

**Comment by tasn** [comment]
I'm closing this ticket as your issue is solved, please let me know if it's not the case.

**Comment by zpcc** [comment]
When I used `ALLOWED_HOSTS = ['example.com:1234']` in `etebase_server/settings.py`, django returned `Bad Request (400)`. 

So I tried `ALLOWED_HOSTS = ['example.com']`, and modified `django_etebase/views.py` like `elif not settings.DEBUG and host.split(':', 1)[0] != request.get_host().split(':', 1)[0]:`, it works now.

**Comment by tasn** [comment]
Interesting, though makes sense...
@zpcc, would you like to open a PR with this fix? Or would you rather I just fix it myself?

Thanks!

**Comment by tasn** [comment]
Oops, didn't mean to re-open, as the original question was indeed a question that's been resolved.

**Comment by zpcc** [comment]
I haven't tested it on other platforms, so maybe it will be better to fix it by you.
