### ISSUE TITLE
Offer a lifetime pricing plan

### ISSUE THREAD

**Issue by impredicative** [etesync/server#76]
I apologize for this request being submitted in the wrong place, but I think it deserves to be on public record. I request that the paid EteSync service provide a lifetime plan. Typically a lifetime of use can perhaps be modeled on average as 25 years (but the service would not be restricted to any such number). Because the subscriber pays all at once, a substantial discount is offered. I advise providing a full lifetime plan for the cost of 10 years, i.e. $240, and certainly no higher than $288. Obviously, if you make it $288 instead of $240, fewer users will subscribe to it, and so it could hurt. Either way, this will get your company a little extra cash when it probably needs it the most. As a prospective subscriber, this will also give me significant peace of mind to know that I can continue to use the service.

**Comment by tasn** [comment]
Sorry for the slow delay, it's been a very busy week!
It's indeed not the right place for this, but let's leave it here for the lack of a better place for it.

We've been discussing it internally since you brought this up and still haven't decided. We'll try to figure it out in the next few weeks, but in case we don't, please follow up with us.

Thanks for bringing this up!

**Comment by jahway603** [comment]
I would also be interested in this. Last comment on this was from a year ago.

**Comment by tasn** [comment]
@jahway603, it's a hard one. :/
What do you think is reasonable pricing for a lifetime? Same as suggested by @impredicative ?

**Comment by BirdInFire** [comment]
> I would also be interested in this. Last comment on this was from a year ago.

Would not recommend to pay, go check that, they don't really care about your security : https://github.com/etesync/server/issues/123

In resume 25 security issue from High yo low unfixed.

So lifetime plan ? yeah if you want to have a piece of software not secured at all why not

**Comment by tasn** [comment]
> Would not recommend to pay, go check that, they don't really care about your security : https://github.com/etesync/server/issues/123
> 
> In resume 25 security issue from High yo low unfixed only in 1 library (from many).
> 
> So lifetime plan ? yeah if you want to have a piece of software not secured at all why not

@BirdInFire, this is untrue and misinformed. I appreciate the concern, and the reporting, but it's based on incorrect assumptions. Take a look at my comment here: https://github.com/etesync/server/issues/123#issuecomment-1070644715

**Comment by TetradoToxinTTX** [comment]
I think $50-$75 is fair for lifetime. 
I'm willing to pay for that amount.
