### ISSUE TITLE
Confirmation links ending with a dash are not properly handled by Thunderbird

### ISSUE THREAD

**Issue by codedust** [etesync/server#77]
When a confirmation code sent via mail by the EteSync server contains a dash ("-") as its last character, the dash is not part of the clickable link in Thunderbird.

E.g. https://dashboard.etebase.com/user/partner/dashboard/?sesame=AAAAAAAAAAAAAAAAAAAA- will be interpreted as [https://dashboard.etebase.com/user/partner/dashboard/?sesame=AAAAAAAAAAAAAAAAAAAA](https://dashboard.etebase.com/user/partner/dashboard/?sesame=AAAAAAAAAAAAAAAAAAAA)- instead of [https://dashboard.etebase.com/user/partner/dashboard/?sesame=AAAAAAAAAAAAAAAAAAAA-](https://dashboard.etebase.com/user/partner/dashboard/?sesame=AAAAAAAAAAAAAAAAAAAA-) (mind the small difference in the link location).

**Comment by tasn** [comment]
:sob: 
Will open a ticket with sesame ASAP and will add a workaround (append `&a=a` to the URL).

Thanks for reporting!

**Comment by tasn** [comment]
I'm closing it as it's going to be fixed in Thunderbird. From the Django Sesame ticket:

- Thunderbird accepted the issue as a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1418548
- Youtube has the same issue, and I think they have more users than django-sesame ;-)
