### ISSUE TITLE
Suggestions for wiki documents

### ISSUE THREAD

**Issue by beatbaozi** [etesync/server#80]
Thank contributors for the great project.  It makes possible for freshman like me to build own etesync server. I dit it in a fresh Debian 10 Buster system and find the wiki documents is not totally compatible.

In Basic Setup, after install _**python3-virtualenv**_, it's written **_virtualenv -p python3 .venv  # If doesn't work, try: virtualenv3 .venv_**. But in Debian 10 both **_virtualenv_** and **_virtualenv3_** command doesn't exist, and **_python3 -m virtualenv_** makes it works.

In Production setup, _**pip3 install daphne**_ is not enough to start daphne. It shows some module missing, thus I tried _**pip install daphne Django django-cors-headers djangorestframework drf-nested-routers msgpack PyNaCl**_ to make it works. Maybe still some module missed? 

Additionally, in Basic Setup the enviroment folder is **_.venv_** while in Production setup and next etebase_server.service chapter it is **_venv_**. I think it would be better to use the same path.

Thanks

**Comment by tasn** [comment]
Feel free to update the wiki, I think it's globally editable. :)
I'm closing this ticket as it's "solved", because you can just edit the wiki.

> In Production setup, pip3 install daphne is not enough to start daphne. It shows some module missing, thus I tried pip install daphne Django django-cors-headers djangorestframework drf-nested-routers msgpack PyNaCl to make it works. Maybe still some module missed?

It's actually `pip install -r requirements.txt`, please add it too if not there.

Thanks a lot for your help!
