### ISSUE TITLE
Installing server (Ubuntu) - Permission denied

### ISSUE THREAD

**Issue by Yippee38** [etesync/server#85]
Following the instructions on installing the Etesync server on Ubuntu 20.04, I get to the step that says:
pip3 install -r requirements.txt

I get the error:
ERROR:  Could not install packages due to an EnvironmentError:  [Errno 13] Permission denied: '/home/<user>/etebase/.venv/lib/python3.8/site-packages/pycparser' Consider using the '--user' option or check the permissions.

I cannot use the --user option because it gives this error:
ERROR:  Can not (sic) perform a '--user' install.  User site-packages are not visible in this virtualenv.

Obviously, I'm not linux expert, and certainly not on virtual environments.  But this second error seems to indicate that I can't run a --user install because of the virtualenv.

pycparser doesn't exist in the directory listed in the first error.  I'm guessing that it should be created by the preceding instruction, but I could be wrong.

What am I doing wrong?

**Comment by tasn** [comment]
You forgot to "get in" the virtualenv, that is: `source .venv/bin/activate`. After that you'll just be able to install using pip without a problem.
Please come to https://www.etesync.com/community-chat/ if you have any additional questions.
